before_install:
- source install-jdk.sh --feature ea

install:
- jshell --execution local ./build.jsh
- JARS="target/build/jars"
- FILES="-Dfile=$JARS/bach.jar -Dsources=$JARS/bach-sources.jar -Djavadoc=$JARS/bach-javadoc.jar"
- find $JARS
- mvn install:install-file $FILES -DgroupId=$GROUP -DartifactId=bach -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
