dist: xenial
language: java

install:
- java --version

script:
- jshell ./build.jsh

after_success:
- BACH=${TRAVIS_BUILD_DIR}/src/main/Bach.java

#- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
#- ./bootstrap.sh

- cd ${TRAVIS_BUILD_DIR}/demo/jigsaw-quick-start/greetings
- java ${BACH}

- cd ${TRAVIS_BUILD_DIR}/demo/jigsaw-quick-start/greetings-world-with-main-and-test
- java -Dbach.level=ALL ${BACH}
