dist: xenial
language: java

install:
- java --version

script:
- java src/bach/Bach.java -

after_success:
- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.sh

#- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
#- ./build-01-hello-world.jsh
