dist: xenial
language: java

install:
- java --version

script:
- ./build.jsh

after_success:
- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.jsh

- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
- echo "./build-01-hello-world.jsh"
