dist: xenial
language: java

install:
- java --version

script:
- jshell ./build.jsh

after_success:
#- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
#- ./bootstrap.sh

#- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
#- java ../../src/bach/Bach.java

#- cd $TRAVIS_BUILD_DIR/demo/02-testing
#- java ../../src/bach/Bach.java
