dist: xenial
language: java

install:
- java --version

script:
- jshell ./build.jsh

after_success:
#- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
#- ./bootstrap.sh

- cd ${TRAVIS_BUILD_DIR}/demo/jigsaw-quick-start/greetings
- java ../../../src/main/Bach.java

- cd ${TRAVIS_BUILD_DIR}/demo/jigsaw-quick-start/greetings-world-with-main-and-test
- java ${TRAVIS_BUILD_DIR}/src/main/Bach.java build
