dist: xenial
language: java

install:
- java --version

script:
- java src/bach/Bach.java -

# https://github.com/sormuras/bach/issues/43
#after_success:
#- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
#- ./bootstrap.jsh

#- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
#- ./build-01-hello-world.jsh
